// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"myproject/internal/controller"
	"myproject/internal/dao"
	"myproject/internal/service"
)

// Injectors from wire.go:

func initApp() (*App, func(), error) {
	db, err := dao.NewDb()
	if err != nil {
		return nil, nil, err
	}
	client, err := dao.NewRedis()
	if err != nil {
		return nil, nil, err
	}
	daoDao := dao.NewDao(db, client)
	serviceService := service.NewService(daoDao)
	controllerController := controller.NewController(serviceService)
	app := NewApp(controllerController, serviceService, daoDao)
	return app, func() {
	}, nil
}
