[db]
# 本地forge数据库
dsn = "root:@tcp(127.0.0.1:3306)/forge?timeout=5s&readTimeout=5s&writeTimeout=5s&parseTime=true&loc=Local&charset=utf8mb4,utf8"
# 最大线程数20个 空闲线程数10 空闲最大时间4h
active = 20
idle = 10
idleTimeout = "4h"
# 查询超时时间200毫秒 执行超时时间300毫秒 事务超时时间400毫秒
queryTimeout = "200ms"
execTimeout = "300ms"
tranTimeout = "400ms"


[redis]
addr = "127.0.0.1"
port = 26379



[domain]
baidu = "http://www.baidu.com"


[http]
host="127.0.0.1"
port=8088